trigger:
  tags:
    include:
      - "*"

resources:
  - repo: self

variables:
  - name: dockerfilePath
    value: "$(Build.SourcesDirectory)/Dockerfile"
  - name: context
    value: "$(Build.SourcesDirectory)"
  - name: tag
    value: "$(Build.BuildId)"
  - name: vmImageName
    value: "ubuntu-latest"
  - group: 'AWS_LLAVE'

#=========================================================================================================

stages:
- stage: Despliegue_desarrollo_datacenter
  displayName: Despliegue en entorno desarrollo datacenter
  jobs:
  - job: desplieguedev
    displayName: Despliegue desarrollo en datacenter
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Compilación de imagen DOCKER.
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        buildContext: $(context)
        repository: "myra-clientlogin-dev"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'), endsWith(variables['Build.SourceBranchName'], '-dev'))

    - task: ECRPushImage@1
      displayName: Subida de imagen a ECR (versión tag).
      inputs:
        awsCredentials: "AWSECR"
        regionName: "us-east-1"
        imageSource: "imagename"
        sourceImageName: "myra-clientlogin-dev"
        sourceImageTag: $(tag)
        pushTag: $(Build.SourceBranchName)
        repositoryName: "myra-clientlogin-dev"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'), endsWith(variables['Build.SourceBranchName'], '-dev'))

    - task: ECRPushImage@1
      displayName: Subida de imagen a ECR (versión latest).
      inputs:
        awsCredentials: "AWSECR"
        regionName: "us-east-1"
        imageSource: "imagename"
        sourceImageName: "myra-clientlogin-dev"
        sourceImageTag: $(tag)
        pushTag: latest
        repositoryName: "myra-clientlogin-dev"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'), endsWith(variables['Build.SourceBranchName'], '-dev'))


#==========================================================================================================================================================================

- stage: Despliegue_produccion
  displayName: Despliegue en entorno produccion
  jobs:
  - job: desplieguepro
    displayName: Despliegue produccion
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Compilación de imagen DOCKER.
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        buildContext: $(context)
        repository: "myra-clientlogin"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'), endsWith(variables['Build.SourceBranchName'], '-v'))

    - task: ECRPushImage@1
      displayName: Subida de imagen a ECR (versión tag).
      inputs:
        awsCredentials: "AWSECR"
        regionName: "us-east-1"
        imageSource: "imagename"
        sourceImageName: "myra-clientlogin"
        sourceImageTag: $(tag)
        pushTag: $(Build.SourceBranchName)
        repositoryName: "myra-clientlogin"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'), endsWith(variables['Build.SourceBranchName'], '-v'))

    - task: ECRPushImage@1
      displayName: Subida de imagen a ECR (versión latest).
      inputs:
        awsCredentials: "AWSECR"
        regionName: "us-east-1"
        imageSource: "imagename"
        sourceImageName: "myra-clientlogin"
        sourceImageTag: $(tag)
        pushTag: latest
        repositoryName: "myra-clientlogin"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'), endsWith(variables['Build.SourceBranchName'], '-v'))